name: Build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  coverage:
    uses: ./.github/workflows/coverage.yml
    secrets: inherit
  docs-deploy:
    uses: ./.github/workflows/docs-deploy.yml
  tests:
    needs: coverage
    uses: ./.github/workflows/tests.yml
