name: Docs Check

on:
  workflow_call:
  pull_request:
    branches: [ main ]

jobs:
  docs-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Run Poetry image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: "1.3.0"

      - name: Install requirements
        run: |
          poetry install --only docs

      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"

      - uses: actions/upload-artifact@v1
        with:
          name: DocumentationHTML
          path: docs/build/html/
